# Generated by Django 5.2.17 on 2026-09-23 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fms_sales_code', models.CharField(blank=True, max_length=50, verbose_name='Mã sales Sota')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Nhân viên kinh doanh',
                'verbose_name_plural': 'Nhân viên kinh doanh',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('client', 'Khách hàng'), ('vendor', 'Nhà cung cấp')], max_length=10, verbose_name='Loại')),
                ('file_name', models.CharField(max_length=200, verbose_name='Tên file')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('partner_ids', models.JSONField(default=list, verbose_name='ID đối tác đã xuất')),
                ('exceptions', models.JSONField(default=list, verbose_name='Ngoại lệ')),
                ('csv', models.TextField(verbose_name='Nội dung CSV')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người xuất')),
            ],
            options={
                'verbose_name': 'Lô xuất Sota',
                'verbose_name_plural': 'Lô xuất Sota',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='Bắt đổi mật khẩu khi đăng nhập')),
                ('failed_attempts', models.PositiveIntegerField(default=0, verbose_name='Số lần sai')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='Khoá đến')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bảo mật đăng nhập',
                'verbose_name_plural': 'Bảo mật đăng nhập',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_no', models.CharField(blank=True, editable=False, max_length=20, verbose_name='Số yêu cầu')),
                ('type', models.CharField(choices=[('client', 'Khách hàng'), ('vendor', 'Nhà cung cấp')], editable=False, max_length=10, verbose_name='Loại')),
                ('state', models.CharField(choices=[('draft', 'Nháp'), ('in_review', 'Đang duyệt'), ('changes_requested', 'Yêu cầu chỉnh sửa'), ('escalated', 'Chờ cấp trên duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Từ chối'), ('exported', 'Đã xuất Sota')], default='draft', editable=False, max_length=20, verbose_name='Trạng thái')),
                ('round', models.PositiveIntegerField(default=0, editable=False, verbose_name='Vòng duyệt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tạo lúc')),
                ('submitted_at', models.DateTimeField(editable=False, null=True, verbose_name='Gửi duyệt lúc')),
                ('decided_at', models.DateTimeField(editable=False, null=True, verbose_name='Quyết định lúc')),
                ('last_exported_at', models.DateTimeField(editable=False, null=True, verbose_name='Xuất Sota lần cuối')),
                ('changed_since_export', models.BooleanField(default=False, editable=False, verbose_name='Thay đổi sau khi xuất')),
                ('legal_name', models.CharField(max_length=300, verbose_name='Tên pháp lý')),
                ('legal_name_normalized', models.CharField(db_index=True, editable=False, max_length=300)),
                ('mst', models.CharField(blank=True, db_index=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\d{10}(-\\d{3})?$', "MST phải gồm 10 chữ số, hoặc 10 chữ số + '-' + 3 chữ số (chi nhánh).")], verbose_name='MST')),
                ('foreign_reg_no', models.CharField(blank=True, max_length=100, verbose_name='Số đăng ký nước ngoài')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ đăng ký')),
                ('country', models.CharField(default='Việt Nam', max_length=100, verbose_name='Quốc gia')),
                ('payment_terms_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Thời hạn thanh toán (ngày)')),
                ('currency', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD'), ('EUR', 'EUR')], default='VND', max_length=3, verbose_name='Tiền tệ thanh toán')),
                ('service_scope', models.CharField(blank=True, help_text='VD: cước, hải quan, vận tải, kho', max_length=300, verbose_name='Phạm vi dịch vụ')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('duplicate_justification', models.TextField(blank=True, help_text='Bắt buộc nếu hệ thống cảnh báo trùng MST/tên.', verbose_name='Lý do tạo dù trùng')),
                ('client_code', models.CharField(blank=True, help_text='Do Tài chính nhập.', max_length=50, verbose_name='Mã khách hàng')),
                ('invoice_name', models.CharField(blank=True, max_length=300, verbose_name='Tên xuất hoá đơn')),
                ('invoice_address', models.CharField(blank=True, max_length=500, verbose_name='Địa chỉ xuất hoá đơn')),
                ('invoice_email', models.EmailField(blank=True, max_length=254, verbose_name='Email nhận HĐĐT')),
                ('credit_limit_vnd', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Hạn mức công nợ đề xuất (VND)')),
                ('expected_monthly_revenue_vnd', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Doanh thu dự kiến/tháng (VND)')),
                ('pass_through', models.BooleanField(default=False, verbose_name='Có thu hộ / chi hộ')),
                ('pass_through_desc', models.TextField(blank=True, verbose_name='Mô tả thu hộ / chi hộ')),
                ('registration_link', models.URLField(blank=True, verbose_name='Link ĐKKD (SharePoint)')),
                ('contract_link', models.URLField(blank=True, verbose_name='Link hợp đồng/báo giá (SharePoint)')),
                ('vendor_type', models.CharField(blank=True, choices=[('carrier', 'Hãng vận chuyển'), ('coloader', 'Co-loader'), ('agent', 'Đại lý nước ngoài'), ('trucker', 'Nhà xe'), ('customs', 'Đại lý hải quan'), ('warehouse', 'Kho')], max_length=20, verbose_name='Loại NCC')),
                ('requesting_department', models.CharField(blank=True, max_length=200, verbose_name='Bộ phận đề xuất')),
                ('licence_link', models.URLField(blank=True, verbose_name='Link giấy phép (SharePoint)')),
                ('insurance_link', models.URLField(blank=True, verbose_name='Link chứng nhận bảo hiểm (SharePoint)')),
                ('rate_agreement_link', models.URLField(blank=True, verbose_name='Link thoả thuận giá (SharePoint)')),
                ('requester', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('sales_rep', models.ForeignKey(blank=True, limit_choices_to={'active': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='onboarding.salesrep', verbose_name='Nhân viên kinh doanh')),
            ],
            options={
                'verbose_name': 'Đối tác',
                'verbose_name_plural': 'Đối tác',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('role_title', models.CharField(blank=True, max_length=200, verbose_name='Chức danh')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Điện thoại')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='onboarding.partner')),
            ],
            options={
                'verbose_name': 'Người liên hệ',
                'verbose_name_plural': 'Người liên hệ',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người viết')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='onboarding.partner')),
            ],
            options={
                'verbose_name': 'Bình luận',
                'verbose_name_plural': 'Bình luận',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Hành động')),
                ('before', models.JSONField(null=True, verbose_name='Trước')),
                ('after', models.JSONField(null=True, verbose_name='Sau')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='onboarding.partner')),
            ],
            options={
                'verbose_name': 'Nhật ký',
                'verbose_name_plural': 'Nhật ký',
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onboarding.partner',),
        ),
        migrations.CreateModel(
            name='VendorRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Nhà cung cấp',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onboarding.partner',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('finance', 'Tài chính'), ('legal', 'Pháp chế'), ('approver', 'Cấp trên')], editable=False, max_length=10, verbose_name='Loại duyệt')),
                ('round', models.PositiveIntegerField(editable=False, verbose_name='Vòng')),
                ('decision', models.CharField(choices=[('approve', 'Duyệt'), ('approve_cond', 'Duyệt có điều kiện'), ('changes', 'Yêu cầu chỉnh sửa'), ('reject', 'Từ chối')], max_length=15, verbose_name='Quyết định')),
                ('conditions_text', models.TextField(blank=True, verbose_name='Điều kiện')),
                ('comment', models.TextField(blank=True, verbose_name='Nhận xét')),
                ('evidence_link', models.URLField(blank=True, verbose_name='Link bằng chứng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Lúc')),
                ('mst_active', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='MST đang hoạt động (tra cứu thuế)')),
                ('invoice_complete', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Thông tin hoá đơn đầy đủ')),
                ('terms_in_policy', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Thời hạn thanh toán đúng chính sách')),
                ('credit_justified', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Hạn mức phù hợp doanh thu')),
                ('prepayment_required', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Cần tạm ứng/đặt cọc')),
                ('pass_through_agreed', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Đã thống nhất xử lý thu hộ/chi hộ')),
                ('currency_clear', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Điều khoản tiền tệ rõ ràng')),
                ('registration_verified', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Đã xác minh ĐKKD')),
                ('signatory_verified', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Đã xác minh thẩm quyền ký')),
                ('standard_contract', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Dùng hợp đồng mẫu')),
                ('deviation_summary', models.TextField(blank=True, verbose_name='Tóm tắt sai khác hợp đồng')),
                ('liability_ok', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Điều khoản trách nhiệm/bảo hiểm chấp nhận được')),
                ('commodity_ok', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Hàng hoá không bị hạn chế')),
                ('screening_done', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Đã sàng lọc đối tượng hạn chế')),
                ('nda_required', models.CharField(blank=True, choices=[('Y', 'Có'), ('N', 'Không'), ('NA', 'N/A')], max_length=2, verbose_name='Cần NDA')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='onboarding.partner', verbose_name='Đối tác')),
                ('reviewer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
            ],
            options={
                'verbose_name': 'Kết quả duyệt',
                'verbose_name_plural': 'Kết quả duyệt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApproverDecision',
            fields=[
            ],
            options={
                'verbose_name': 'Duyệt cấp trên',
                'verbose_name_plural': 'Duyệt cấp trên',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onboarding.review',),
        ),
        migrations.CreateModel(
            name='FinanceReview',
            fields=[
            ],
            options={
                'verbose_name': 'Duyệt Tài chính',
                'verbose_name_plural': 'Duyệt Tài chính',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onboarding.review',),
        ),
        migrations.CreateModel(
            name='LegalReview',
            fields=[
            ],
            options={
                'verbose_name': 'Duyệt Pháp chế',
                'verbose_name_plural': 'Duyệt Pháp chế',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('onboarding.review',),
        ),
    ]
